services:
  user-service:
    build:
      context: ./user-service
      dockerfile: src/main/docker/Dockerfile.native
    ports:
      - "8081:8080"

  weather-service:
    build:
      context: ./weather-service
      dockerfile: src/main/docker/Dockerfile.native
    ports:
      - "8082:8080"

  notification-service:
    build:
      context: ./notification-service
      dockerfile: src/main/docker/Dockerfile.native
    ports:
      - "8084:8080"
