version: "3.10"

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      - user-postgres
      - weather-service
      - notification-service
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://user-postgres:5432/userdb
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: secret
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
      WEATHER_SERVICE_URL: http://weather-service:8082
      NOTIFICATION_SERVICE_URL: http://notification-service:8084
    networks:
      - backend

  user-postgres:
    image: postgres:16
    container_name: user-postgres
    restart: always
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - user_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  weather-service:
    build:
      context: ./weather-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: weather-service
    ports:
      - "8082:8082"
    depends_on:
      - weather-postgres
      - notification-service
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://weather-postgres:5432/weatherdb
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: secret
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
      NOTIFICATION_SERVICE_URL: http://notification-service:8084
    networks:
      - backend

  weather-postgres:
    image: postgres:16
    container_name: weather-postgres
    restart: always
    environment:
      POSTGRES_DB: weatherdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - weather_pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - backend

  notification-service:
    build:
      context: ./notification-service
      dockerfile: src/main/docker/Dockerfile.native
    container_name: notification-service
    ports:
      - "8084:8084"
    depends_on:
      - notification-postgres
    volumes:
        - ./secrets/serviceAccountKey.json:/secrets/serviceAccountKey.json:ro
    environment:
      SERVICE_ACCOUNT_PATH: /secrets/serviceAccountKey.json
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://notification-postgres:5432/notificationdb
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: secret
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
    networks:
      - backend

  notification-postgres:
    image: postgres:16
    container_name: notification-postgres
    restart: always
    environment:
      POSTGRES_DB: notificationdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - notification_pg_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - backend

volumes:
  user_pg_data:
  weather_pg_data:
  notification_pg_data:

networks:
  backend:
