apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-alert-ingress
  namespace: weather-alert
  annotations:
    #cert-manager.io/cluster-issuer: "letsencrypt-prod" 
    #nginx.ingress.kubernetes.io/healthcheck-path: "/health"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    #nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  # - host: weatheralert.blaz040.me
  # #- host: 4.232.242.151.sslip.io
  #   http:
  #     paths:
  #     - path: /user(/|$)(.*)
  #       pathType: ImplementationSpecific
  #       backend:
  #         service:
  #           name: user-service
  #           port:
  #              number: 8080
  - host: blaz040.me
  #- host: 4.232.242.151.sslip.io
    http:
      paths:
      - path: /user(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: user-service
            port:
              number: 8080
      - path: /weather(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: weather-service
            port:
              number: 8082
      - path: /notification(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: notification-service
            port:
              number: 8084
      
      # tls:
  # - hosts: 
  #   - 4.232.242.151.sslip.io
  #   secretName: weather-alert-tls # Cert-manager will create this secret
  # tls:
  # - hosts: 
  #   - blaz040.me
  #   - weatheralert.blaz040.me
  #   secretName: weather-alert-tls # Cert-manager will create this secret
  
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: demo-ingress
#   annotations:
#     kubernetes.io/ingress.class: nginx
# spec:
#   rules:
#   - host: demo.local
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: demo-service
#             port:
#               number: 80