apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: weather-alert
data:
  QUARKUS_DATASOURCE_DB_KIND: postgresql
  #QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://user-postgres:5432/userdb
  QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://shared-postgres:5432/maindb
  QUARKUS_DATASOURCE_USERNAME: postgres
  QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
  WEATHER_SERVICE_URL: http://weather-service:8082
  NOTIFICATION_SERVICE_URL: http://notification-service:8084
